### ISSUE TITLE
Automatic deployments

### ISSUE THREAD

**Issue by uesteibar** [frutinder/frutinder#5]
Right now the deployment is a manual process (running `npm run release`), plus it resets the setting for the custom domain.

It would be better to have this process automated by releasing the code to production whenever a new commits lands on master. We could solve this by using [netlify](https://www.netlify.com/).

**Comment by uesteibar** [comment]
It's running on https://upbeat-knuth-af5ccc.netlify.com/ already, if you folks are ok with it I'll switch the domain to point to this site.

**Comment by xsimov** [comment]
Looks good on my end! Go for it!

**Comment by uesteibar** [comment]
It's live at https://frutinder.com 🎉
